export default {
    CREDENTIAL_ACTIVE_TEXT: "#030303",
    THEME: "#003b95",
    WHITE: "#FFFFFF",
    BLUE: "#006ce4",
    ACTIVE_NAVIGATION_COLOR: "#006ce4",
    DISABLED_NAVIGATION_COLOR: "#EAEAEA",
    PROFILE_IMAGE_BG: "#BEE4D0",
    DEACTIVE: "#eeeeee",
    DARK_GRAY: "#aaaaaa",
    DISABLED_TXT: "#2b2b2b",
    THEME_TRANSPARENT: "#395f9d",
    LOCATION_CONTAINER: "#e8f2fa",
    FADE: "#A9A9A9",
    RATINGS_BG: "#00a24e"
}